title: Snehith Reddy Kathi
logo: /images/ProfilePicture.jpg
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal

email: kathisnehithreddy@gmail.com
Linkedin: linkedin.com/snehithreddykathi
